# -*- mode: org; mode: flyspell; ispell-local-dictionary: "hu" -*-
#+OPTIONS: toc:nil
#+TITLE: Diszkrét Matematika 2 Vizsga\-tematika
#+AUTHOR: Mikecz Márk László
#+EMAIL: mikecz.mark.laszlo[at]gmail[dot]com
#+LANGUAGE: hu

* Gráfok
** Definíciók
*** Irányítatlan Gráfok
    Irányítatlan gráf; izolált csúcs; illeszkedési reláció; két csúcs
    szomszédos; üres gráf; hurok\-él; párhuzamos él (többszörös él);
    véges gráf; végtelen gráf; fok\-szám; fok\-számok összege és élek
    száma közötti összefüggés; \(n\)-reguláris gráf; reguláris gráf;
    gráfok izomorfiája; gráfok Descartes--szorzat; páros gráf
    (két\-részes gráf); rész\-gráf; szuper\-gráf; telített rész\-gráf;
    rész\-gráfnak a komplementere; egyszerű gráf komplementere; séta;
    vonal; út; kör; össze\-függőség; komponensek; fa; erdő;
    feszítő\-fa; feszítő\-erdő; vágás; erdő; Euler--vonal;
    Ha\-mil\-ton--út; Hamilton--kör; címkézett és súlyozott gráf.
*** Irányított Gráf
    Irányított gráf; irányított gráf megfordítása; szigorúan
    párhuzamos él; csúcs ki\-foka; csúcs be\-foka; ki\-fok összege,
    be\-fok összege és élek száma közötti összefüggés; irányított
    gráfok izomorfiája; véges gráfok él\-listás ábrázolása; irányított
    rész\-gráf; irányított séta; irányított vonal; irányított út;
    irányított kör; erős össze\-függőség; erős komponensek; irányított
    fa; jól\-színezés; kromatikus szám; gráfok mátrixai; síkban
    rajzolható gráf; Euler formula; topologikus izomorfia; Kuratowski
    tétel.
** Tételek
*** Bizonyítás nélkül
    Dirac és Ore tétel
     (https://hu.wikipedia.org/wiki/Hamilton-k%C3%B6r); Dijkstra
     módszer (7.2.22).
*** Bizonyítással
**** Állíŧás arról hogyan lehet sétából utat kapni (7.1.20)
**** Állítás a zárt vonalak jellemzéséről körökkel (7.1.21)
**** Fa ekvivalens definícióira vonatkozó tétel (7.1.29)
**** Kör\-mentes fák és első\-fokú csúcsok kapcsolatát leíró állítás (7.1.30)
**** Fákban, a csúcsok és élek számának összefüggését leíró tétel (7.1.31)
**** Összefüggő gráf feszítő\-fáinak létezésére vonatkozó állítás (7.1.37)
**** Összefüggő gráfban, körök számára vonatkozó tétel (7.1.38)
**** Összefüggő gráfban, vágások számára vonatkozó tétel (7.1.41)
**** Összefüggő véges gráfban Zárt Euler--vonal létezéséről, illetve él\-diszjunkt vonalakra való felbontására vonatkozó tétel (7.1.45)
**** Kruskal algoritmus
* Algebra
** Definíciók
*** Csoportok
    Grupoid; fél\-csoport; (jobboldali, baloldali) egység elem;
    monoid; (jobboldali, baloldali) inverz; csoport; Abel--csoport;
    homomorfizmus; monomorfizmus; epimorfizmus; izomorfizmus;
    endomorfizmus; automorfizmus; rész\-fél\-csoport; rész\-csoport;
    Klein csoport; generátum; ciklikus csoport; diéder csoport;
    csoport rendje; elem rendje; jobb és baloldali mellék\-osztályok;
    normálosztó; faktor\-csoport; homomorfizmus magja; direkt szorzat.
*** Gyűrűk és testek
    Gyűrű; null\-osztó\-mentes gyűrű; kommutatív gyűrű; integritási
    tartomány; egység\-elemes integritási tartomány; ferde\-testek;
    testek; $példa gyűrűre (\mathbb{Z}[\alhpa])$; gyűrű
    homomorfizmusok; gyűrű karakterisztikája;
    Frobenius--endomorfizmus; rész\-gyűrű; ideál; mellék\-osztályok;
    faktor\-gyűrű; példa faktor\-gyűrűre; homomorfizmus magja; gyűrűk
    direkt szorzata; Gauss--gyűrűk; példa gyűrűre ami nem
    Gauss--gyűrű; Euklideszi gyűrűk; hányados\-test.
** Tételek
*** Bizonyítás nélkül
**** Ciklikus csoport rész\-csoportjait és generátorait leíró tétel (8.1.41)
**** Prímszám\-rendű ciklikus csoportokra vonatkozó tétel (8.1.55)
**** Véges Abel--csoportok alap\-tétele (8.1.93)
**** Cayley tétel (8.1.102)
*** Bizonyítással
**** Asszociativitás, egység\-elem, inverz és kommutatív elemek homomorf képeiről szóló tétel és az ide tartozó következmény (8.1.8 és 8.1.9)
**** Csoport ekvivalens definícióiról szóló tétel és az egyszerűsítési szabály (8.1.13 8.1.14)
**** Rész\-csoport ekvivalens definícióiról szóló állítás (8.1.27 és 8.1.28)
**** Rész\-csoportok metszetére vonatkozó következmény (8.1.29)
**** Generátumot jellemző állítás és a ciklikus csoportokra vonatkozó következmény (8.1.33 8.1.34)
**** Ciklikus csoportokat leíró tétel (8.1.38)
**** Ciklikus csoportok rész\-csoportjára vonatkozó tétel (8.1.40)
**** Lagrange tétel és következményei (8.1.52, 8.1.53 és 8.1.54)
**** Normálosztó ekvivalens definícióira vonatkozó tétel (8.1.71)
**** Normálosztók metszetére vonatkozó tétel (8.1.72)
**** Normálosztó szerinti mellék\-osztályok és a művelet kapcsolatára vonatkozó tétel és az ide tartozó következmény (8.1.80 és 8.1.81)
**** Homomorfizmus\-tétel (8.1.85)
**** Gyűrű homomorf képére vonatkozó tétel (8.2.18)
**** Nullosztó\-mentes gyűrűben a nem nulla elemek additív rendjére vonatkozó tétel (8.2.19)
**** Gyűrűben ideál szerinti mellék\-osztályokra és a műveletre vonatkozó tétel és az ide tartozó következmény (8.2.48 és 8.2.49)
**** Gyűrű homomorfizmus--tétel (8.2.54)
**** Kommutatív egység\-elemes gyűrűben a fő\-ideálokra vonatkozó tétel és a hozzá tartozó következmény (8.2.65 és 8.2.66)
**** Gauss gyűrűben a prím és irreducibilis elemek kapcsolata (8.2.67 vége)
**** Euklideszi gyűrű elemei és a $\varphi$ függvény kapcsolatára vonatkozó állítás (8.2.70) 
**** Bővített Euklideszi algoritmus Euklideszi gyűrűben (8.2.75)
**** Euklideszi gyűrűben a prímek és felbonthatatlan kapcsolatára vonatkozó tétel (8.2.76)
**** Euklideszi gyűrű és Gauss--gyűrű kapcsolatára vonatkozó tétel (8.2.77)
* Polinomok
** Definíciók
*** Polinomok
   Formális hatvány sorok gyűrűje és a rajta értelmezett műveletek
   $(R[\![x]\!], +, \cdot)$; $(R[x],+,\cdot)$ egy\-határozatlanú
   polinom gyűrű és rajta értelmezett műveletek; konstans polinom;
   együttható; konstans tag; fő\-együttható; fő\-tag; polinom foka;
   null\-polinom; lineáris polinom; monom; fő\-polinom
   (normál\-polinom); polinom\-függvény; pszeudo\-osztás;
   Horner--elrendezés.
*** Többszörös gyökök
    Algebrai derivált; többszörös gyökök; primitív polinomok; Lagrange
    interpoláció; titok\-megosztás.
** Tételek
*** Bizonyítás nélkül
**** $R$ elemei megfeleltetése \(R[x]\)-ben
**** $R$ tulajdonságai és $R[x]$ tulajdonságai kapcsolatára vonatkozó állítás
**** Wilson tétel
**** Algebrai derivált tulajdonságai 
**** Irreducibilis polinomok és test\-bővítés (8.3.40)
**** Véges testek elem\-száma és a megjegyzés (8.3.54, 8.3.55 és 8.3.61)
**** Véges testek alap tétele (8.3.110)
**** Véges testek multiplikatív csoportjára vonatkozó tétel (8.3.58)
**** Irreducibilis polinomok (8.3.64)
**** Gauss tétele (8.3.68)
**** Schönemann-Eisenstein-tétel (8.3.77)
*** Bizonyítással
**** Maradékos osztás tétele polinomokra (8.3.8)
**** Gyök\-tényező leválasztása (8.3.9)
**** Polinom gyökére és fok\-számára vonatkozó következmény (8.3.10)
**** Két polinom megegyezésére vonatkozó következmény (8.3.11)
**** Polinom és polinom\-függvény kapcsolatát leíró következmény (8.3.12)
**** Test feletti polinom gyűrűre vonatkozó következmény (8.3.13)
**** Egy polinom osztói és deriváltját leíró tétel és az ide tartozó következmény (8.3.31 és 8.3.32)
**** Többszörös gyökökre és a deriváltra vonatkozó tétel és megjegyzés (8.3.34 és 8.3.35)
* Kódolás
** Definíciók
*** Forrás kódolás
    Gyakoriság; relatív gyakoriság egyedi információ\-tartalom;
    információ egysége; entrópia (vagy átlagos információ\-tartalom);
    relatív entrópia; felbontható (vagy egyértelműen dekódolható, vagy
    veszteség\-mentes) kód; betűnkénti kódolás; kód\-fa; prefix kód;
    egyenletes kód; vesszős kód; átlagos szó\-hossz; optimális kód.
*** Hiba\-korlátozó kódolás
    Paritás\-bit; \(t\)-hiba\-jelző kód, pontosan \(t\)-hiba\-jelző
    kód; Hamming távolság; Hamming súly; minimális távolságú
    dekódolás; \(t\)-hiba\-javító kód, pontosan \(t\)-hiba\-javító
    kód; tökéletes kód; MDS kód; lineáris kód; generátor mátrix;
    ellenőrző mátrix; szindróma; polinom kód; ciklikus kód.
** Tételek
*** Bizonyítás nélkül
**** McMillan-egyenlőtlenség (9.2.9)
**** Shannon tétele zajmentes csatornákra (9.2.15)
**** Shannon-kód létezése és Huffman kód (9.2.16 és 9.2.18)
**** Szindróma dekódolás (9.3.15)
*** Bizonyítással
**** Hamming korlát (9.3.11)
**** Singleton korlát (9.3.12)
