# -*- mode: org; mode: flyspell; ispell-local-dictionary: "hu" -*-
#+SETUPFILE: inc-zh.org
#+TITLE:
#+AUTHOR:
#+DATE:

* Diszkrét matematika II. - első ZH - 2016-03-17. Név: 
  1. Van--e olyan 8 pontú egyszerű gráf, melyben a csúcsok foka rendre
     #+ATTR_LATEX: :environment inparaenum
     1) 6, 6, 6, 5, 4, 3, 1, 1;
     2) 7, 7, 5, 5, 4, 4, 4, 3;
     3) 7, 3, 3, 4, 4, 4, 1, 0.
     4) 6, 6, 5, 4, 4, 4, 4, 3;

  2. Legyen $F=(\varphi,E,V)$ egy *fa* ahol $V=\{1,2,\ldots,n\}$ és
     $n\in\mathbb{N}$ és $p$ egy üres tömb. Keresd meg az első fokú
     csúcsok közül a legkisebb sorszámút, töröld a fából, majd tárold
     el a(z egyetlen) szomszédjának sorszámát a $p$ tömb végére majd
     rekurzívan hajtsd végre ezeket a lépéseket a maradék gráfra amíg
     lehetséges. Az így kapott $n-1$ hosszú sorozat a fa Prüfer
     kódja. Keresd meg az alábbi gráfok minimális súlyú feszítő\-fáját
     (mondjuk Kruskal algoritmussal) és határozd meg a Prüfer
     kódjukat!

     #+ATTR_LATEX: :environment inparaenum
     1) 
	#+BEGIN_LaTeX
	\begin{tikzpicture}
	\foreach \i 
	in {0,1,2}{
	\foreach[evaluate=\j as \ij using int(\j*3+\i+1)] \j 
	in {0,1,2}{ \draw (\i, \j) node[draw] (\ij) {\ij}; } };
	\draw 
	(3) edge[below] node{10} (2)
	(1) edge[left]  node{3}  (4)
	(4) edge[above] node{9}  (5)
	(2) edge[left]  node{3}  (5)
	(5) edge[above] node{8}  (6)
	(6) edge[right] node{9}  (3)
	(6) edge[right] node{4}  (9)
	(9) edge[above] node{5}  (8)
	(7) edge[left]  node{8}  (4)
	;
	\end{tikzpicture}
	#+END_LaTeX
     2) 
	#+BEGIN_LaTeX
	\begin{tikzpicture}
	\foreach \i 
	in {0,1,2}{
	\foreach[evaluate=\j as \ij using int(\j*3+\i+1)] \j 
	in {0,1,2}{ \draw (\i, \j) node[draw] (\ij) {\ij}; } };
	\draw 
	(1) edge[below] node{1}  (2)
	(1) edge[left]  node{2}  (4)
	(6) edge[above] node{3}  (5)
	(2) edge[right] node{4}  (5)
	(2) edge[below] node{5}  (7)
	(6) edge[right] node{6}  (3)
	(6) edge[right] node{7}  (9)
	(9) edge[above] node{8}  (8)
	(7) edge[above] node{9}  (8)
	(2) edge[below] node{10}  (3)
	(5) edge[left]  node{11}  (8)
	(7) edge[left]  node{12}  (4)
	;
	\end{tikzpicture}
	#+END_LaTeX
     3) Illetve rajzold le a $p=[56456569]$ Prüfer kódhoz tartozó fát!
  3. Bizonyítsd be, hogy egy gráf pontosan akkor páros ha nem
     tartalmaz páratlan hosszú kört.
  4. Legyen $e$ a $G$ csoport egység\-eleme, és $f,g\in G$. Igazoljuk, hogy
     #+ATTR_LATEX: :environment inparaenum
     1) ha $f^3 = e = g^4$ és $gf = fg^3$, akkor $fg = gf$;
     2) ha $f^2 = e = g^6$ és $fg = g^4f$, akkor $g^3 = e$ és $fg = gf$.
  5. Legyen $n=15$ és jelölje $D_n$ diéder csoport a szabályos
     \(n\)-szög egybevágó leképezéseit ahol a $\varepsilon$ az
     óramutató forgásának ellentétes irányba ($\circlearrowleft$)
     $\frac{2\pi}{n}$ radiánnal való forgatást a $\tau$ pedig a
     függőleges szimmetria tengelyre való tükrözést jelöli.

     Legyen $g_1=\varepsilon^6 \circ \tau^3 \circ \varepsilon^5 \circ
     \tau^8 \circ \varepsilon^{13} \circ \tau^{21}$ és $g_2=\tau^2 \circ
     \varepsilon^{44} \circ \tau$.
     #+ATTR_LATEX: :environment inparaenum
     1) Soroljuk fel $D_n$ elemeit!
     2) Egyszerűsítsd $g_1$ és $g_2$ elemet.
     3) Mi $g_1$, $g_2$ illetve $g_1\circ g_2$ rendje?
     4) Soroljuk fel $\langle g_1\rangle$, $\langle g_2\rangle$ és
        $\langle g_1,g_2 \rangle$ elemeit.
  6. Bizonyítsd be, hogy $(\Z_{11}^*,\cdot)$ és $(\Z_{22}^*,\cdot)$
     azonos rendű ciklikus csoportok! Következik--e ebből, hogy
     izomorfak?  Ha igenlő a válasz, akkor adj meg egy-egy generátort
     és az izomorfizmust a két csoport között (ellenkező esetben,
     bizonyítsd be hogy nem igaz).
\vfill

* Diszkrét matematika II. - első ZH - 2016-03-17. Név: 
  1. Van--e olyan 8 pontú egyszerű gráf, melyben a csúcsok foka rendre
     #+ATTR_LATEX: :environment inparaenum
     1) 6, 6, 6, 5, 4, 3, 1, 1;
     2) 7, 7, 5, 5, 4, 4, 4, 3;
     3) 7, 3, 3, 4, 4, 4, 1, 0.
     4) 6, 6, 5, 4, 4, 4, 4, 3;

  2. Legyen $F=(\varphi,E,V)$ egy *fa* ahol $V=\{1,2,\ldots,n\}$ és
     $n\in\mathbb{N}$ és $p$ egy üres tömb. Keresd meg az első fokú
     csúcsok közül a legkisebb sorszámút, töröld a fából, majd tárold
     el a(z egyetlen) szomszédjának sorszámát a $p$ tömb végére majd
     rekurzívan hajtsd végre ezeket a lépéseket a maradék gráfra amíg
     lehetséges. Az így kapott $n-1$ hosszú sorozat a fa Prüfer
     kódja. Keresd meg az alábbi gráfok minimális súlyú feszítő\-fáját
     (mondjuk Kruskal algoritmussal) és határozd meg a Prüfer
     kódjukat!

     #+ATTR_LATEX: :environment inparaenum
     1) 
	#+BEGIN_LaTeX
	\begin{tikzpicture}
	\foreach \i 
	in {0,1,2}{
	\foreach[evaluate=\j as \ij using int(\j*3+\i+1)] \j 
	in {0,1,2}{ \draw (\i, \j) node[draw] (\ij) {\ij}; } };
	\draw 
	(3) edge[below] node{10} (2)
	(1) edge[left]  node{3}  (4)
	(4) edge[above] node{9}  (5)
	(2) edge[left]  node{3}  (5)
	(5) edge[above] node{8}  (6)
	(6) edge[right] node{9}  (3)
	(6) edge[right] node{4}  (9)
	(9) edge[above] node{5}  (8)
	(7) edge[left]  node{8}  (4)
	;
	\end{tikzpicture}
	#+END_LaTeX
     2) 
	#+BEGIN_LaTeX
	\begin{tikzpicture}
	\foreach \i 
	in {0,1,2}{
	\foreach[evaluate=\j as \ij using int(\j*3+\i+1)] \j 
	in {0,1,2}{ \draw (\i, \j) node[draw] (\ij) {\ij}; } };
	\draw 
	(1) edge[below] node{1}  (2)
	(1) edge[left]  node{2}  (4)
	(6) edge[above] node{3}  (5)
	(2) edge[right] node{4}  (5)
	(2) edge[below] node{5}  (7)
	(6) edge[right] node{6}  (3)
	(6) edge[right] node{7}  (9)
	(9) edge[above] node{8}  (8)
	(7) edge[above] node{9}  (8)
	(2) edge[below] node{10}  (3)
	(5) edge[left]  node{11}  (8)
	(7) edge[left]  node{12}  (4)
	;
	\end{tikzpicture}
	#+END_LaTeX
     3) Illetve rajzold le a $p=[56456569]$ Prüfer kódhoz tartozó fát!
  3. Bizonyítsd be, hogy egy gráf pontosan akkor páros ha nem
     tartalmaz páratlan hosszú kört.
  4. Legyen $e$ a $G$ csoport egység\-eleme, és $f,g\in G$. Igazoljuk, hogy
     #+ATTR_LATEX: :environment inparaenum
     1) ha $f^3 = e = g^4$ és $gf = fg^3$, akkor $fg = gf$;
     2) ha $f^2 = e = g^6$ és $fg = g^4f$, akkor $g^3 = e$ és $fg = gf$.
  5. Legyen $n=15$ és jelölje $D_n$ diéder csoport a szabályos
     \(n\)-szög egybevágó leképezéseit ahol a $\varepsilon$ az
     óramutató forgásának ellentétes irányba ($\circlearrowleft$)
     $\frac{2\pi}{n}$ radiánnal való forgatást a $\tau$ pedig a
     függőleges szimmetria tengelyre való tükrözést jelöli.

     Legyen $g_1=\varepsilon^6 \circ \tau^3 \circ \varepsilon^5 \circ
     \tau^8 \circ \varepsilon^{13} \circ \tau^{21}$ és $g_2=\tau^2 \circ
     \varepsilon^{44} \circ \tau$.
     #+ATTR_LATEX: :environment inparaenum
     1) Soroljuk fel $D_n$ elemeit!
     2) Egyszerűsítsd $g_1$ és $g_2$ elemet.
     3) Mi $g_1$, $g_2$ illetve $g_1\circ g_2$ rendje?
     4) Soroljuk fel $\langle g_1\rangle$, $\langle g_2\rangle$ és
        $\langle g_1,g_2 \rangle$ elemeit.
  6. Bizonyítsd be, hogy $(\Z_{11}^*,\cdot)$ és $(\Z_{22}^*,\cdot)$
     azonos rendű ciklikus csoportok! Következik--e ebből, hogy
     izomorfak?  Ha igenlő a válasz, akkor adj meg egy-egy generátort
     és az izomorfizmust a két csoport között (ellenkező esetben,
     bizonyítsd be hogy nem igaz).
* COMMENT Prüfer nem felhasznált
  1. Legyen $p_1, p_2, \ldots, p_{n-1}$ egy sorozat ahol $p_{n-1}=n$,
     $p_i \in \{1, 2, \ldots n\}$ és $n\in \mathbb{N}$.  Legyen $s_1$
     a legkisebb szám \(1\)-től \(n-1\)-ig amelyik nem szerepel a
     $p_1, p_2, \ldots, p_{n-1}$ sorozatban, illetve $s_{i+1}$ a
     legkisebb ilyen szám amelyik nem szerepel a $s_1, s_2, \ldots,
     s_i, p_{i+1}, p_{i+2}, \ldots, p_{n-1}$ sorozatban.  Az üres $n$
     csúcsot tartalmazó gráfból kiindulva, minden \(i\)-re (ahol $1\le
     i \le n-1$), kössük össze az $s_i$ és $p_i$ csúcsokat.
